[project]
name = "slork"
version = "0.2.0"
dependencies = [
    "pyyaml",
    "dacite"
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
